### ISSUE TITLE
Rename repository name

### ISSUE THREAD

**Issue by filhocf** [dsoares/Roundcube-Plugin-RemoveAttachments#11]
Hi @dsoares 

I saw some roundcube plugin developers align your plugin project names to "roundcube-".

So, I suggest to you rename this project to "roundcube-remove_attachment".

And thanks by your work.

**Comment by dsoares** [comment]
Thank you by your suggestion. I renamed it to roundcube-removeattachments and also renamed all my public roundcube plugins.
