### ISSUE TITLE
zh_CN.inc

### ISSUE THREAD

**Issue by wei790205141** [dsoares/Roundcube-Plugin-RemoveAttachments#13]
<?php
$labels = array();
$labels['removeall'] = '删除所有附件';
$labels['removeattachment'] = '删除这个附件';

$messages = array();
$messages['removeoneconfirm'] = '您确定删除这个附件？';
$messages['removeallconfirm'] = '您确定删除所有附件？';
$messages['removing'] = '正在删除...';
$messages['attachmentremoved'] = '附件已删除';
$messages['removefailed'] = '错误: 此附件未能删除';

?>

**Comment by dsoares** [comment]
This is not an issue. 
I don't know how to translate to zh_CN. Did you mean to do a PR (pull request) ?

**Comment by wei790205141** [comment]
Many people in China use RC, so I hope this plug-in has Chinese, translated for you!


mis-jack wei
On 2/1/2018 22:11，dsoares<notifications@github.com> wrote：

This is not an issue.
I don't know how to translate to zh_CN. Did you mean to do a PR (pull request) ?

**Comment by dsoares** [comment]
Hi,
I understand but i don't know Chinese, so i can't really translate it.
You would be very welcome to contribute to this project with a PR with a chinese translation.
