### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by nodo50** [dsoares/Roundcube-Plugin-RemoveAttachments#3]
Hi dsoares, thanks for the plugin!. Here the spanish translation, I hope you like to add to the plugin.
best regards
[es_ES.inc.txt](https://github.com/dsoares/Roundcube-Plugin-RemoveAttachments/files/243854/es_ES.inc.txt)

**Comment by dsoares** [comment]
Spanish translation added to [release 0.2.3](https://plugins.roundcube.net/packages/dsoares/removeattachments).
Thank you for your contribution! :)
