### ISSUE TITLE
version number in composer.json

### ISSUE THREAD

**Issue by nodo50** [dsoares/Roundcube-Plugin-RemoveAttachments#4]
Hi Dsoares, I know it is a dumb issue, but could you add the tag version in composer.json?

"version": "0.2.3",

It will facilitate to automatically track the status of many roundcube instalations at once.
Thanks in advance.

**Comment by dsoares** [comment]
Done. Thank you for the suggestion.

**Comment by dsoares** [comment]
Done. Thank you for the suggestion.
