### ISSUE TITLE
removing attacment marks mail unread

### ISSUE THREAD

**Issue by wanradt** [dsoares/Roundcube-Plugin-RemoveAttachments#5]
Marking mail unread has undesirable side effect: you get some unread mails **somewhere** in mail folder. 

Consider this: you sort mails by size to clean up huge attachments, then you remove attachments from some mail, folder is reloaded and this mail is sorted away from your reach (because it is now tiny) and marked as unread.  Now you have a unread message somewhere in your folder. Seems not neccessary to mark it unread.

**Comment by dsoares** [comment]
It was not intencionally marked as unread, the plugin creates a new message to replace the one with the attachment, so it was naturally flagged as unseen.
But i agree with you and now the plugin marks the message as seen (92ff4e9ea79d4ebfb8894af9c99f1fe5c682f5ce, release <a href="https://github.com/dsoares/Roundcube-Plugin-RemoveAttachments/releases/tag/0.2.5">0.2.5</a>).
