### ISSUE TITLE
Preserve timestamp of original message

### ISSUE THREAD

**Issue by mandresen** [dsoares/Roundcube-Plugin-RemoveAttachments#6]
Hi and thanks for your excellent work on this and other RoundCube plugins.

Would it be possible to change the behaviour when creating the new message without the deleted attachment, so that the file creation timestamp of the original message is preserved?

When the "new" mail gets the current date as timestamp, it throws off scripts that process mails based on date.

**Comment by dsoares** [comment]
Done in release 0.2.8.
Sorry for the late answer.
